export ZSH=/home/vagrant/.oh-my-zsh       
 
ZSH_THEME="robbyrussell"     

plugins=(git)        

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:\/usr/games:/usr/local/games"                     

source $ZSH/oh-my-zsh.sh    

export EDITOR='vim'

alias emacs="TERM=xterm-256color emacs -nw"
